name: timelinetracker
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  geocoding: ^2.0.2
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.1

  flutter_facebook_auth: ^3.5.0
  google_sign_in : ^5.0.4

  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

